// <auto-generated />
using Api.Verbs.Dictionary.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Verbs.Dictionary.Migrations
{
    [DbContext(typeof(EnglishVerbsContext))]
    partial class EnglishVerbsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Verbs.Dictionary.Models.Verbs", b =>
                {
                    b.Property<string>("present")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("past")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pastParticiple")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pronuciation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("spanish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("present");

                    b.ToTable("Verbs");
                });
#pragma warning restore 612, 618
        }
    }
}
